name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Inject EmailJS Secrets into environment.prod.ts
        run: |
          npm install ts-node
          npx ts-node scripts/set-env.ts
        env:
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
          EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}

      - name: Build Angular Project
        run: |
          npx ng build --configuration production --output-path docs --base-href /my-portfolio/ --deploy-url /my-portfolio/
          mv docs/browser/* docs/
          rm -rf docs/browser

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACTION_DEPLOY_TOKEN }}
          publish_dir: ./docs
